import { db, cardsTable } from "@workspace/db";
import { eq } from "drizzle-orm";

// Official image URL format: https://en.onepiececardgame.com/system/web/card/en_OP01-001.png
// For local images, copy files to artifacts/api-server/public/cards/ and use:
// imageUrl: "/api/static/cards/OP01-001.png"
const BASE_IMG = "https://en.onepiececardgame.com/system/web/card/en_";
const BASE_IMG_LOCAL = "/api/static/cards/";

const sampleCards = [
  // OP01 Leaders
  {
    cardNumber: "OP01-001",
    name: "Monkey D. Luffy",
    cardType: "leader",
    color: "red",
    rarity: "L",
    setCode: "OP01",
    cost: null,
    power: 5000,
    counter: null,
    attribute: "Strike",
    life: 5,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[Activate: Main] [Once Per Turn] Give up to 1 DON!! card from your cost area to 1 of your Characters.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-001.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP01-002",
    name: "Roronoa Zoro",
    cardType: "leader",
    color: "green",
    rarity: "L",
    setCode: "OP01",
    cost: null,
    power: 5000,
    counter: null,
    attribute: "Slash",
    life: 4,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[Your Turn] You may rest up to 1 of your DON!! cards. If you do, up to 1 of your Characters gains +1000 power until end of turn.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-002.png`,
    keywords: [],
  },

  // OP01 Characters
  {
    cardNumber: "OP01-016",
    name: "Nami",
    cardType: "character",
    color: "green",
    rarity: "C",
    setCode: "OP01",
    cost: 1,
    power: 1000,
    counter: 2000,
    attribute: "Special",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText: "[On Play] Draw 1 card, then trash 1 card from your hand.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-016.png`,
    keywords: ["On Play"],
  },
  {
    cardNumber: "OP01-017",
    name: "Usopp",
    cardType: "character",
    color: "green",
    rarity: "C",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    counter: 1000,
    attribute: "Ranged",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText: null,
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-017.png`,
    keywords: [],
  },
  {
    cardNumber: "OP01-025",
    name: "Sanji",
    cardType: "character",
    color: "red",
    rarity: "UC",
    setCode: "OP01",
    cost: 3,
    power: 5000,
    counter: 1000,
    attribute: "Strike",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText: "[Blocker]",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-025.png`,
    keywords: ["Blocker"],
  },
  {
    cardNumber: "OP01-028",
    name: "Tony Tony Chopper",
    cardType: "character",
    color: "blue",
    rarity: "C",
    setCode: "OP01",
    cost: 2,
    power: 3000,
    counter: 1000,
    attribute: "Wisdom",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[On Play] Your opponent selects 1 card from their hand and places it on the top of their deck.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-028.png`,
    keywords: ["On Play"],
  },
  {
    cardNumber: "OP01-033",
    name: "Nico Robin",
    cardType: "character",
    color: "purple",
    rarity: "UC",
    setCode: "OP01",
    cost: 3,
    power: 4000,
    counter: 1000,
    attribute: "Wisdom",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[When Attacking] Look at 5 cards from the top of your deck and place them on top of the deck in any order.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-033.png`,
    keywords: ["When Attacking"],
  },
  {
    cardNumber: "OP01-036",
    name: "Franky",
    cardType: "character",
    color: "blue",
    rarity: "R",
    setCode: "OP01",
    cost: 5,
    power: 7000,
    counter: 1000,
    attribute: "Strike",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText: null,
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-036.png`,
    keywords: [],
  },
  {
    cardNumber: "OP01-041",
    name: "Brook",
    cardType: "character",
    color: "purple",
    rarity: "R",
    setCode: "OP01",
    cost: 4,
    power: 6000,
    counter: 1000,
    attribute: "Slash",
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText: "[Rush]",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-041.png`,
    keywords: ["Rush"],
  },
  {
    cardNumber: "OP01-053",
    name: "Shanks",
    cardType: "character",
    color: "red",
    rarity: "SR",
    setCode: "OP01",
    cost: 10,
    power: 12000,
    counter: null,
    attribute: "Slash",
    life: null,
    cardTypes: "Four Emperors / Red Hair Pirates",
    effectText: "[On Play] K.O. all Characters with 7000 power or less.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-053.png`,
    keywords: ["On Play"],
  },
  {
    cardNumber: "OP01-060",
    name: "Trafalgar Law",
    cardType: "character",
    color: "blue",
    rarity: "SR",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    counter: 1000,
    attribute: "Slash",
    life: null,
    cardTypes: "Heart Pirates / The Worst Generation",
    effectText:
      "[Activate: Main] [Once Per Turn] You may rest this Character: Choose 1 of your opponent's Characters with 0 DON!! attached and K.O. it.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-060.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP01-061",
    name: "Eustass Kid",
    cardType: "character",
    color: "red",
    rarity: "SR",
    setCode: "OP01",
    cost: 4,
    power: 5000,
    counter: null,
    attribute: "Special",
    life: null,
    cardTypes: "Kid Pirates / The Worst Generation",
    effectText:
      "[On Play] Up to 1 of your Leader or Character cards gains +2000 power during this turn.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-061.png`,
    keywords: ["On Play"],
  },
  {
    cardNumber: "OP01-062",
    name: "Portgas D. Ace",
    cardType: "character",
    color: "red",
    rarity: "SR",
    setCode: "OP01",
    cost: 5,
    power: 6000,
    counter: null,
    attribute: "Special",
    life: null,
    cardTypes: "Whitebeard Pirates",
    effectText: "[Rush] [On Play] Deal 1 damage to your opponent.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-062.png`,
    keywords: ["Rush", "On Play"],
  },

  // OP01 Events
  {
    cardNumber: "OP01-080",
    name: "Gomu Gomu no Storm",
    cardType: "event",
    color: "red",
    rarity: "R",
    setCode: "OP01",
    cost: 3,
    power: null,
    counter: null,
    attribute: null,
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[Main] Your Leader or 1 of your Characters gains +6000 power during this turn.",
    triggerEffect:
      "[Trigger] Your Leader or 1 of your Characters gains +2000 power during this turn.",
    imageUrl: `${BASE_IMG_LOCAL}OP01-080.png`,
    keywords: [],
  },
  {
    cardNumber: "OP01-081",
    name: "Oni Giri",
    cardType: "event",
    color: "green",
    rarity: "UC",
    setCode: "OP01",
    cost: 2,
    power: null,
    counter: null,
    attribute: null,
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if your opponent has 4 or less cards in their hand, draw 2 cards.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-081.png`,
    keywords: [],
  },
  {
    cardNumber: "OP01-082",
    name: "Diable Jambe",
    cardType: "event",
    color: "red",
    rarity: "R",
    setCode: "OP01",
    cost: 3,
    power: null,
    counter: null,
    attribute: null,
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[Main] K.O. up to 1 of your opponent's Characters with 5000 power or less.",
    triggerEffect:
      "[Trigger] K.O. up to 1 of your opponent's Characters with 3000 power or less.",
    imageUrl: `${BASE_IMG_LOCAL}OP01-082.png`,
    keywords: [],
  },

  // OP02 Cards
  {
    cardNumber: "OP02-001",
    name: "Trafalgar Law",
    cardType: "leader",
    color: "blue/yellow",
    rarity: "L",
    setCode: "OP02",
    cost: null,
    power: 5000,
    counter: null,
    attribute: "Slash",
    life: 4,
    cardTypes: "Heart Pirates",
    effectText:
      "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand: Swap up to 1 of your opponent's Characters with 1 of your Characters.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP02-001.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP02-002",
    name: "Eustass Kid",
    cardType: "leader",
    color: "red/green",
    rarity: "L",
    setCode: "OP02",
    cost: null,
    power: 5000,
    counter: null,
    attribute: "Special",
    life: 4,
    cardTypes: "Kid Pirates",
    effectText:
      "[Activate: Main] [Once Per Turn] You may rest 3 of your DON!! cards: Up to 1 of your Characters gains 4000 power until end of turn.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP02-002.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP02-013",
    name: "Bepo",
    cardType: "character",
    color: "blue",
    rarity: "UC",
    setCode: "OP02",
    cost: 2,
    power: 3000,
    counter: 1000,
    attribute: "Strike",
    life: null,
    cardTypes: "Heart Pirates",
    effectText:
      "[On Play] If your Leader has the {Heart Pirates} type, return up to 1 of your opponent's Characters with a cost of 3 or less to their hand.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP02-013.png`,
    keywords: ["On Play"],
  },
  {
    cardNumber: "OP02-046",
    name: "Charlotte Katakuri",
    cardType: "character",
    color: "black",
    rarity: "SR",
    setCode: "OP02",
    cost: 7,
    power: 8000,
    counter: null,
    attribute: "Special",
    life: null,
    cardTypes: "Big Mom Pirates",
    effectText:
      "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand: Add up to 1 card from the top of your deck to your hand.",
    triggerEffect: "[Trigger] Play this card.",
    imageUrl: `${BASE_IMG_LOCAL}OP02-046.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP02-099",
    name: "Big Mom",
    cardType: "character",
    color: "yellow",
    rarity: "SR",
    setCode: "OP02",
    cost: 9,
    power: 10000,
    counter: null,
    attribute: "Special",
    life: null,
    cardTypes: "Four Emperors / Big Mom Pirates",
    effectText:
      "[On Play] You may return any number of Characters you control to your hand: This Character gains +1000 power for each Character returned this way until end of turn.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP02-099.png`,
    keywords: ["On Play"],
  },

  // OP03 Cards
  {
    cardNumber: "OP03-001",
    name: "Donquixote Doflamingo",
    cardType: "leader",
    color: "purple",
    rarity: "L",
    setCode: "OP03",
    cost: null,
    power: 5000,
    counter: null,
    attribute: "Special",
    life: 5,
    cardTypes: "Donquixote Pirates",
    effectText:
      "[Activate: Main] [Once Per Turn] You may discard 1 card from your hand: 1 of your opponent's Characters gains [Blocker] until the end of your opponent's next turn.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP03-001.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP03-022",
    name: "Crocodile",
    cardType: "character",
    color: "black",
    rarity: "SR",
    setCode: "OP03",
    cost: 6,
    power: 8000,
    counter: null,
    attribute: "Special",
    life: null,
    cardTypes: "The Seven Warlords of the Sea",
    effectText:
      "[On Play] Select up to 1 of your opponent's Leader or Character cards. It cannot attack during your opponent's next turn.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP03-022.png`,
    keywords: ["On Play"],
  },

  // OP01 Stages
  {
    cardNumber: "OP01-089",
    name: "Thousand Sunny",
    cardType: "stage",
    color: "green",
    rarity: "R",
    setCode: "OP01",
    cost: 2,
    power: null,
    counter: null,
    attribute: null,
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText:
      "[Activate: Main] [Once Per Turn] Give 1 active DON!! card from your cost area to 1 of your Leader or Character cards.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-089.png`,
    keywords: ["Activate: Main"],
  },
  {
    cardNumber: "OP01-090",
    name: "Going Merry",
    cardType: "stage",
    color: "red",
    rarity: "C",
    setCode: "OP01",
    cost: 1,
    power: null,
    counter: null,
    attribute: null,
    life: null,
    cardTypes: "Straw Hat Crew",
    effectText: "[Your Turn] All of your Characters gain +1000 power.",
    triggerEffect: null,
    imageUrl: `${BASE_IMG_LOCAL}OP01-090.png`,
    keywords: [],
  },
];

async function seed() {
  console.log("Seeding cards...");

  for (const card of sampleCards) {
    await db
      .insert(cardsTable)
      .values({
        cardNumber: card.cardNumber,
        name: card.name,
        cardType: card.cardType,
        color: card.color,
        rarity: card.rarity,
        setCode: card.setCode,
        cost: card.cost ?? null,
        power: card.power ?? null,
        counter: card.counter ?? null,
        attribute: card.attribute ?? null,
        effectText: card.effectText ?? null,
        triggerEffect: card.triggerEffect ?? null,
        life: card.life ?? null,
        cardTypes: card.cardTypes ?? null,
        imageUrl: card.imageUrl ?? null,
        keywords: card.keywords ?? [],
      })
      .onConflictDoUpdate({
        target: cardsTable.cardNumber,
        set: { imageUrl: card.imageUrl ?? null, name: card.name },
      });
  }

  console.log(`Seeded ${sampleCards.length} cards successfully.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
